### ISSUE TITLE
Unable to complete the installation of Wordpress from the Browser

### ISSUE THREAD

**Issue by wagnerbento** [dawidkotarba/docker-wordpress-mariadb-swag-ssl#1]
Hi Dawid.

How are you?

I followed your tutorial, but the installation of wordpress via browser is not working, when I type my URL, it is directing to an html from Linux Server, and not the Wordpress installer.

Please can you help me fix this?

Thanks

**Comment by wagnerbento** [comment]
Hi Dawid.

Thanks for the feedback.

I believe I'm doing something wrong. In docker-compose.yml I add the lines below?


server {
	listen 80;
	listen [::]:80;
	server_name _;
	return 301 https://$host$request_uri;
}

server {
	listen 443 ssl http2 default_server;
	listen [::]:443 ssl http2 default_server;

	root /var/www/html/example;
	index index.html index.htm index.php;

	server_name _;

	include /config/nginx/proxy-confs/*.subfolder.conf;

	include /config/nginx/ssl.conf;

	client_max_body_size 0;

	location / {
		try_files $uri $uri/ /index.php?$args @app;
	}

	location @app {
		proxy_pass http://wordpress;
		proxy_set_header Host $host;
        	proxy_redirect off;
        	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        	proxy_set_header X-Forwarded-Proto https;
        	proxy_set_header X-Real-IP $remote_addr;
	}

}

**Comment by dawidkotarba** [comment]
In docker-compose.yml, remove the swag section, so eventually it shall look like that:

```yaml

version: '3.3'
services:

  wordpressdb:
    image: mariadb:latest
    container_name: wordpressdb
    volumes:
      - "./database:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress-db-password
      MYSQL_DATABASE: wordpress

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    hostname: wordpress
    depends_on:
      - wordpressdb
    restart: always
    links:
      - wordpressdb:mysql
    ports:
      - "8080:80"
    volumes:
      - "./html:/var/www/html"
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress-db-password

```

Then, spawn images by doing `docker-compose up` and check if WordPress responds (port 8080).

**Comment by dawidkotarba** [comment]
Hi Wagner, it may happen that the lastest version of SWAG made issues with this setup. Please use `linuxserver/swag:1.26.0-ls123` instead:

```yaml
version: '3.3'
services:

  wordpressdb:
    image: mariadb:latest
    container_name: wordpressdb
    volumes:
      - "./database:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress-db-password
      MYSQL_DATABASE: wordpress

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    hostname: wordpress
    depends_on:
      - wordpressdb
    restart: always
    links:
      - wordpressdb:mysql
    ports:
      - "8080:80"
    volumes:
      - "./html:/var/www/html"
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress-db-password

  swag:
    image: linuxserver/swag:1.26.0-ls123
    container_name: swag
    depends_on:
      - wordpress
    restart: always
    volumes:
      - ./config:/config
      - ./default:/config/nginx/site-confs/default
    environment:
      - EMAIL=youremail@something.com
      - URL=yoursite.com
      - SUBDOMAINS=www
      - VALIDATION=http
      - TZ=Europe/London
      - PUID=500
      - PGID=500
    ports:
      - "443:443"
      - "80:80"
```
